version: '3'

volumes:
    postgres-data:
        driver: local

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    #ports:
    #  - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - traefik-proxy
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    #ports:
    #  - "16543:80"
    networks:
      - traefik-proxy
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-proxy"
        - "traefik.http.routers.pgadmin.entrypoints=http"
        - "traefik.http.routers.pgadmin.rule=Host(`$PGADMIN_URL`)"
        - "traefik.http.middlewares.pgadmin-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.pgadmin.middlewares=pgadmin-https-redirect"
        - "traefik.http.routers.pgadmin-secure.entrypoints=https"
        - "traefik.http.routers.pgadmin-secure.rule=Host(`$PGADMIN_URL`)"
        - "traefik.http.routers.pgadmin-secure.tls=true"
        #- "traefik.http.routers.pgadmin-secure.tls.certresolver=http"

networks:
  traefik-proxy:
    external: true