apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-dev-certificate
  namespace: sistemax
spec:
  secretName: tls-localhost-dev
  issuerRef:
    name: ca-local-issuer
    kind: ClusterIssuer
  commonName: sistemax.vagrant.test
  dnsNames:
    - sistemax.vagrant.test
    - sistemax.local.test
